server:
    port: 8080

logging:
  level:
    example: DEBUG

spring:
  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:db/test
    platform: hsql
    initialize: false
    # コネクションプール数
#    max-active: 100
#    max-idle: 20
#    min-idle: 20
#    initial-size: 20
    # コネクションタイムアウト対応
    testOnBorrow: true
    validationQuery: SELECT 1